name: Portfolio CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build portfolio
    runs-on: ubuntu-
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          version: latest

      - name: Install Bun version manager
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: build project
        run: bun install --frozen-lockfile && bun run build
